name: ami-setup

on: push

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: build-webapp
          run: |
            ls -al
            pwd
            # cd webapp

