# path of the webapp in runner "/home/runner/work/webapp/webapp"
name: ami-setup

on: push

jobs:
    build:
      runs-on: ubuntu-latest

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: build-webapp
          run: |
            ls -al
            pwd
            # cd ..
        - name: Set up Packer
          uses: hashicorp/setup-packer@main
        
        - name: Install Packer plugins
          run: packer init .
  
        - name: Build Packer Template
          run: packer build ami.us-east-1.pkr.hcl

          

        - name: Zip Checked-Out Files
        # Create a ZIP archive of the checked-out files
          run: |
            ls -al
            pwd
            npm install
            cd ..
            ls -al
            zip -r webapp.zip .
            ls -al
            pwd
            
            
        #  First pwd  above -> /home/runner/work/webapp/webapp
        # Second pwd  above ->/home/runner/work/webapp
