
name: Integ-Testing

# on: [pull_request]
on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: newdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    # - name: Wait for PostgreSQL to be ready
    #   run: |
    #     n=0
    #     until [ $n -ge 5 ]
    #     do
    #       npm run db:migrate:up # Replace with your database migration command
    #       [ $? -eq 0 ] && break
    #       n=$[$n+1]
    #       sleep 15
    #     done

    - name: Run Tests
      env:

        # postgres connection environment variables
        DB_DIALECT: postgres
        DB_HOST: 127.0.0.1
        DB_DATABASE: postgres
        DB_USERNAME: postgres
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_PGPORT: 5432

      run: npm test