name: Integ-Testing

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: newdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Pa55w0rd
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      env:
        # postgres connection environment variables
        DB_DIALECT: postgres
        DB_HOST: 127.0.0.1
        DB_DATABASE: postgres
        DB_USER: postgres
        DB_PASSWORD: Pa55w0rd
        DB_PGPORT: 5432

      run: npm test

  packer-build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2
    
    - name: Set up Packer
      uses: hashicorp/setup-packer@main
    
    - name: Validate Packer Template
      run: packer validate ami.us-east-1.pkr.hcl
