name: Integ-Testing

# on:
#   pull_request:
#     branches:
#       - main
on: 
  push:

jobs:
  packer-validation-build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Zip Repository
      run: |
        ls -al
        pwd
        npm i
        ls -al
        zip -r webapp.zip . -x ".git"
        ls -al
        pwd

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: webapp
        path: webapp.zip
    
    - name: Set up Packer
      uses: hashicorp/setup-packer@main
    
    - name: Install Packer plugins
      run: packer init .
    
    - name: Validate Packer Template
      run: packer validate ami.us-east-1.pkr.hcl

    - name: Format Packer Configuration
      run: |
        if [ -n "$(packer fmt --check ami.us-east-1.pkr.hcl)" ]; then
          echo "Packer configuration needs formatting. Run 'packer fmt' locally and commit the changes.";
          exit 1;
        fi

    - name: Format Packer Template
      run: packer fmt ami.us-east-1.pkr.hcl

